// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as Ochess from "ochess/./ochess.bs.js";

function home_rank(param) {
  if (param) {
    return 0;
  } else {
    return 7;
  }
}

function promotion_rank(param) {
  if (param) {
    return 7;
  } else {
    return 0;
  }
}

function pre_promotion_rank(param) {
  if (param) {
    return 6;
  } else {
    return 1;
  }
}

function coordinate_pairs(turn, param) {
  if (typeof param === "number") {
    if (param === 0) {
      return /* tuple */[
              /* tuple */[
                4,
                turn ? 0 : 7
              ],
              /* tuple */[
                6,
                turn ? 0 : 7
              ]
            ];
    } else {
      return /* tuple */[
              /* tuple */[
                4,
                turn ? 0 : 7
              ],
              /* tuple */[
                2,
                turn ? 0 : 7
              ]
            ];
    }
  } else if (param.tag) {
    return /* tuple */[
            /* tuple */[
              param[1],
              turn ? 6 : 1
            ],
            /* tuple */[
              param[2],
              turn ? 7 : 0
            ]
          ];
  } else {
    return /* tuple */[
            /* tuple */[
              param[0],
              param[1]
            ],
            /* tuple */[
              param[2],
              param[3]
            ]
          ];
  }
}

function string_of_piece_type(param) {
  switch (param) {
    case 0 : 
        return "king";
    case 1 : 
        return "queen";
    case 2 : 
        return "rook";
    case 3 : 
        return "bishop";
    case 4 : 
        return "knight";
    case 5 : 
        return "pawn";
    
  }
}

function string_of_color(param) {
  if (param) {
    return "white";
  } else {
    return "black";
  }
}

var split_on_char = Ochess.split_on_char;

var identical_positions = Ochess.identical_positions;

var draw_by_repetition_aux = Ochess.draw_by_repetition_aux;

var draw_by_repetition = Ochess.draw_by_repetition;

var draw_by_lack_of_progress = Ochess.draw_by_lack_of_progress;

var draw = Ochess.draw;

var opposite_color = Ochess.opposite_color;

var color_sign = Ochess.color_sign;

var piece_chars = Ochess.piece_chars;

var char_of_piece_type = Ochess.char_of_piece_type;

var rassoc = Ochess.rassoc;

var piece_type_of_char = Ochess.piece_type_of_char;

var int_of_letter = Ochess.int_of_letter;

var letter_of_int = Ochess.letter_of_int;

var print_board = Ochess.print_board;

var print_position = Ochess.print_position;

var init_position = Ochess.init_position;

var within_range = Ochess.within_range;

var within_range2 = Ochess.within_range2;

var copy_matrix = Ochess.copy_matrix;

var no_k_castle = Ochess.no_k_castle;

var no_q_castle = Ochess.no_q_castle;

var Illegal_move = Ochess.Illegal_move;

var make_move = Ochess.make_move;

var knight = Ochess.knight;

var rook = Ochess.rook;

var bishop = Ochess.bishop;

var queen = Ochess.queen;

var pawn_white_mv = Ochess.pawn_white_mv;

var pawn_black_mv = Ochess.pawn_black_mv;

var pawn_white_cap = Ochess.pawn_white_cap;

var pawn_black_cap = Ochess.pawn_black_cap;

var add = Ochess.add;

var explore_direction = Ochess.explore_direction;

var explore_directions = Ochess.explore_directions;

var checked_direction = Ochess.checked_direction;

var checked_directions = Ochess.checked_directions;

var checked = Ochess.checked;

var find_king = Ochess.find_king;

var king_checked = Ochess.king_checked;

var empty_segment = Ochess.empty_segment;

var check_castle = Ochess.check_castle;

var castle_moves = Ochess.castle_moves;

var possible_field_simple_moves = Ochess.possible_field_simple_moves;

var possible_moves = Ochess.possible_moves;

var board_center = Ochess.board_center;

var mirror_y = Ochess.mirror_y;

var piece_value = Ochess.piece_value;

var field_value = Ochess.field_value;

var win = Ochess.win;

var delta = Ochess.delta;

var Interrupt = Ochess.Interrupt;

var deadline = Ochess.deadline;

var check_timer = Ochess.check_timer;

var set_timer = Ochess.set_timer;

var del_timer = Ochess.del_timer;

var Illegal_position = Ochess.Illegal_position;

var alpha_beta = Ochess.alpha_beta;

var alpha_beta_search = Ochess.alpha_beta_search;

var legal_moves = Ochess.legal_moves;

var max_depth = Ochess.max_depth;

var alpha_beta_deepening = Ochess.alpha_beta_deepening;

var previous = Ochess.previous;

var print_move = Ochess.print_move;

var is_digit = Ochess.is_digit;

var int_of_char = Ochess.int_of_char;

var parse_move_string = Ochess.parse_move_string;

var parse_move = Ochess.parse_move;

var game_status = Ochess.game_status;

var best_move = Ochess.best_move;

var init_rem_time = Ochess.init_rem_time;

var thinking_interval = Ochess.thinking_interval;

var update_remaining = Ochess.update_remaining;

var parse_time = Ochess.parse_time;

var flush = Ochess.flush;

var parse_level = Ochess.parse_level;

var main = Ochess.main;

export {
  split_on_char ,
  identical_positions ,
  draw_by_repetition_aux ,
  draw_by_repetition ,
  draw_by_lack_of_progress ,
  draw ,
  opposite_color ,
  color_sign ,
  piece_chars ,
  char_of_piece_type ,
  rassoc ,
  piece_type_of_char ,
  int_of_letter ,
  letter_of_int ,
  print_board ,
  print_position ,
  init_position ,
  within_range ,
  within_range2 ,
  copy_matrix ,
  no_k_castle ,
  no_q_castle ,
  Illegal_move ,
  make_move ,
  knight ,
  rook ,
  bishop ,
  queen ,
  pawn_white_mv ,
  pawn_black_mv ,
  pawn_white_cap ,
  pawn_black_cap ,
  add ,
  explore_direction ,
  explore_directions ,
  checked_direction ,
  checked_directions ,
  checked ,
  find_king ,
  king_checked ,
  empty_segment ,
  check_castle ,
  castle_moves ,
  possible_field_simple_moves ,
  possible_moves ,
  board_center ,
  mirror_y ,
  piece_value ,
  field_value ,
  win ,
  delta ,
  Interrupt ,
  deadline ,
  check_timer ,
  set_timer ,
  del_timer ,
  Illegal_position ,
  alpha_beta ,
  alpha_beta_search ,
  legal_moves ,
  max_depth ,
  alpha_beta_deepening ,
  previous ,
  print_move ,
  is_digit ,
  int_of_char ,
  parse_move_string ,
  parse_move ,
  game_status ,
  best_move ,
  init_rem_time ,
  thinking_interval ,
  update_remaining ,
  parse_time ,
  flush ,
  parse_level ,
  main ,
  home_rank ,
  promotion_rank ,
  pre_promotion_rank ,
  coordinate_pairs ,
  string_of_piece_type ,
  string_of_color ,
  
}
/* Ochess Not a pure module */
